# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7df9de8d2babeed46cc93331719064566907f90da28f0a0a324a174d6fb12baa7bb8dce18184b58f2b3818b33edc8831883ebf819f3110b71dad924c9f2097f

test:
  secret_key_base: e00e0985bfce515a4eebe444713f246ecc67f9e0ba5645021b90242186789ebc6e487bcede7fc3673c8d86c9b16d4fa008f6b884b9d6d408cc1e63341b5542cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
